## Getting Started

### Import Libraries

In [15]:
import requests
import json
import pandas as pd

### Import Data

In [16]:
augData = './datasets/Aug_2023.csv'
septData = './datasets/Sept_2023.csv'
octData = './datasets/Oct_2023.csv'


dfAug = pd.read_csv(augData)
dfSept = pd.read_csv(septData)
dfOct = pd.read_csv(octData)

print(dfAug)
print(dfSept)
print(dfOct)

     YEAR_MONTH          DAY_TYPE  TIME_PER_HOUR PT_TYPE        PT_CODE  \
0       2023-08           WEEKDAY             22   TRAIN           NS28
1       2023-08  WEEKENDS/HOLIDAY             22   TRAIN           NS28
2       2023-08  WEEKENDS/HOLIDAY              0   TRAIN      DT10/TE11
3       2023-08           WEEKDAY              0   TRAIN      DT10/TE11
4       2023-08           WEEKDAY             10   TRAIN  EW16/NE3/TE17
...         ...               ...            ...     ...            ...
6815    2023-08  WEEKENDS/HOLIDAY              6   TRAIN           DT23
6816    2023-08  WEEKENDS/HOLIDAY              7   TRAIN  NS27/CE2/TE20
6817    2023-08           WEEKDAY              7   TRAIN  NS27/CE2/TE20
6818    2023-08  WEEKENDS/HOLIDAY             12   TRAIN            SE5
6819    2023-08           WEEKDAY             12   TRAIN            SE5

      TOTAL_TAP_IN_VOLUME  TOTAL_TAP_OUT_VOLUME
0                     752                   311
1                     612                   223
2                      37                   242
3                      86                   445
4                   28179                 39454
...                   ...                   ...
6815                  365                   400
6816                  476                   863
6817                 1283                  8802
6818                 2080                  1213
6819                 3811                  2219

[6820 rows x 7 columns]
     YEAR_MONTH          DAY_TYPE  TIME_PER_HOUR PT_TYPE        PT_CODE  \
0       2023-09  WEEKENDS/HOLIDAY             14   TRAIN           CC16
1       2023-09           WEEKDAY             14   TRAIN           CC16
2       2023-09  WEEKENDS/HOLIDAY             10   TRAIN           EW11
3       2023-09           WEEKDAY             10   TRAIN           EW11
4       2023-09           WEEKDAY              6   TRAIN   NS24/NE6/CC1
...         ...               ...            ...     ...            ...
6816    2023-09           WEEKDAY              6   TRAIN           DT23
6817    2023-09  WEEKENDS/HOLIDAY              7   TRAIN  NS27/CE2/TE20
6818    2023-09           WEEKDAY              7   TRAIN  NS27/CE2/TE20
6819    2023-09  WEEKENDS/HOLIDAY             12   TRAIN            SE5
6820    2023-09           WEEKDAY             12   TRAIN            SE5

      TOTAL_TAP_IN_VOLUME  TOTAL_TAP_OUT_VOLUME
0                    3585                  3153
1                    5869                  5846
2                   10830                  9821
3                   20095                 18338
4                    3553                  8804
...                   ...                   ...
6816                 1917                  2946
6817                  427                   802
6818                 1175                  8034
6819                 2178                  1239
6820                 3458                  1891

[6821 rows x 7 columns]
     YEAR_MONTH          DAY_TYPE  TIME_PER_HOUR PT_TYPE        PT_CODE  \
0       2023-10  WEEKENDS/HOLIDAY             11   TRAIN            NS7
1       2023-10           WEEKDAY             11   TRAIN            NS7
2       2023-10  WEEKENDS/HOLIDAY             16   TRAIN            SW4
3       2023-10           WEEKDAY             16   TRAIN            SW4
4       2023-10  WEEKENDS/HOLIDAY             10   TRAIN            CC5
...         ...               ...            ...     ...            ...
6815    2023-10  WEEKENDS/HOLIDAY              6   TRAIN           DT23
6816    2023-10  WEEKENDS/HOLIDAY              7   TRAIN  NS27/CE2/TE20
6817    2023-10           WEEKDAY              7   TRAIN  NS27/CE2/TE20
6818    2023-10           WEEKDAY             12   TRAIN            SE5
6819    2023-10  WEEKENDS/HOLIDAY             12   TRAIN            SE5

      TOTAL_TAP_IN_VOLUME  TOTAL_TAP_OUT_VOLUME
0                   10207                 11033
1                   20072                 13995
2                    1031                  1107
3                    1985                  2669
4                    1308                  2484
...                   ...                   ...
6815                  482                   393
6816                  392                   765
6817                 1196                  8911
6818                 5001                  2533
6819                 1763                  1030

[6820 rows x 7 columns]

In [17]:
# Combine All DataFrames
dfCombined = pd.concat([dfAug, dfSept, dfOct], ignore_index=True)
print(dfCombined)

# Output Combined DataFrames
output_path = './outputDatasets/combinedData.csv'
dfCombined.to_csv(output_path, index=False)

# To Verify Combination
totalRows = dfAug.shape[0] + dfSept.shape[0] + dfOct.shape[0]
print("Total Rows should be:", totalRows)
if dfAug.shape[1] == dfSept.shape[1] == dfOct.shape[1]:
    print("Number of columns is the same for all three DataFrames:", dfAug.shape[1])

      YEAR_MONTH          DAY_TYPE  TIME_PER_HOUR PT_TYPE        PT_CODE  \
0        2023-08           WEEKDAY             22   TRAIN           NS28
1        2023-08  WEEKENDS/HOLIDAY             22   TRAIN           NS28
2        2023-08  WEEKENDS/HOLIDAY              0   TRAIN      DT10/TE11
3        2023-08           WEEKDAY              0   TRAIN      DT10/TE11
4        2023-08           WEEKDAY             10   TRAIN  EW16/NE3/TE17
...          ...               ...            ...     ...            ...
20456    2023-10  WEEKENDS/HOLIDAY              6   TRAIN           DT23
20457    2023-10  WEEKENDS/HOLIDAY              7   TRAIN  NS27/CE2/TE20
20458    2023-10           WEEKDAY              7   TRAIN  NS27/CE2/TE20
20459    2023-10           WEEKDAY             12   TRAIN            SE5
20460    2023-10  WEEKENDS/HOLIDAY             12   TRAIN            SE5

       TOTAL_TAP_IN_VOLUME  TOTAL_TAP_OUT_VOLUME
0                      752                   311
1                      612                   223
2                       37                   242
3                       86                   445
4                    28179                 39454
...                    ...                   ...
20456                  482                   393
20457                  392                   765
20458                 1196                  8911
20459                 5001                  2533
20460                 1763                  1030

[20461 rows x 7 columns]
Total Rows should be: 20461
Number of columns is the same for all three DataFrames: 7

In [5]:
station_count_per_hour = dfCombined.groupby(['TIME_PER_HOUR', 'PT_CODE']).size().unstack(fill_value=0)

# Displaying the first few rows of the result for a concise view
station_count_per_hour.head(100)

PT_CODE,BP10,BP11,BP12,BP13,BP2,BP3,BP4,BP5,BP6/DT1,BP7,...,TE16,TE18,TE19,TE22,TE3,TE4,TE5,TE6,TE7,TE8
TIME_PER_HOUR,,,,,,,,,,,,,,,,,,,,,
0,1,1,0,2,1,0,0,1,6,1,...,6,6,6,6,6,6,6,6,6,6
5,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
6,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
7,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
8,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
9,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
10,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
11,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
12,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
13,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
14,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
15,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
16,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
17,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
18,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
19,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
20,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
21,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
22,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
23,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6